feat: tratando exceptions de enum
Joaolluiz/Template-Microservice pull request #5
Opened 2024-09-12 16:22 UTC by nathalia-nobrega

## Iniciando tratamento de exceções e inclusão de código feito em outra branch

### Alterações feitas:

**- CustomizedResponseEntityExceptionHandler.java** 
1. Adição de uma nova classe de Exception à anotação @ ExceptionHandler

**- Novo arquivo: InvalidObjectTypeException.java** 
1. Classe que representa um novo tipo de exceção, com status BAD REQUEST, a fim de tratar dados com tipos inválidos.

**- ProjectDTO.java**
1. Inclusão do código feito pelo @lulus3 na branch dele

**- ProjectService.java**
1. Inclusão do código feito pelo @lulus3 na branch dele

**- V0__Create_Table_Project.sql**
1. Inclusão do código feito pelo @lulus3 na branch dele

2024-09-12 20:11 UTC, Joaolluiz requested changes

2024-09-12 20:11 UTC, Joaolluiz commented on src/main/java/br/com/templatemicroservice/dto/ProjectDTO.java
1. Pode retirar o id do DTO;
2. Para Organization e Credentials pode continuar utilizando o tipo do Enum, apenas adicionar a anotação @Enumerated(EnumType.STRING) no atributo;

2024-09-12 20:11 UTC, Joaolluiz commented on src/main/java/br/com/templatemicroservice/exceptions/InvalidObjectTypeException.java
1. Não é necessário o primeiro método, apenas o segundo que recebe como argumento uma String;

2024-09-12 20:11 UTC, Joaolluiz commented on src/main/java/br/com/templatemicroservice/service/ProjectService.java
1. Em relação a validação dos campos, crie um método auxiliar para fazer essa validação, pois será utilizado tanto no método de update quanto de save;
2. Tente implementar dessa maneira o método auxiliar:
private void nomeDoMétodo (ProjectDTO projectDTO) {
    
    EnumSet<Organization> validOrganizations = EnumSet.of(
        Organization.FENIX, 
        Organization.FOXCONN_MOEBG, 
        Organization.FOXCONN_BRASIL
    );

    if (!validOrganizations.contains(Organization.valueOf(projectDTO.getOrganization()))) {
        throw new InvalidObjectTypeException("O valor informado para Organização não é válido (deve ser FENIX, FOXCONN_MOEBG ou FOXCONN_BRASIL)");
    }

    EnumSet<Credential> validCredentials = EnumSet.of(Credential.CATI, Credential.CAPDA);

    if (!validCredentials.contains(Credential.valueOf(projectDTO.getCredential()))) {
        throw new InvalidObjectTypeException("O valor informado para Credencial não é válido (deve ser CATI ou CAPDA)");
    }

2024-09-13 01:43 UTC, nathalia-nobrega commented on src/main/java/br/com/templatemicroservice/dto/ProjectDTO.java
Resolvido!

2024-09-13 01:44 UTC, nathalia-nobrega commented on src/main/java/br/com/templatemicroservice/exceptions/InvalidObjectTypeException.java
Resolvido!

2024-09-13 01:44 UTC, nathalia-nobrega commented on src/main/java/br/com/templatemicroservice/service/ProjectService.java
Resolvido!

2024-09-14 21:17 UTC, closed without merging